//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelMonkey.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TravelMonkey.Resources.LanguageResources", typeof(LanguageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD NEW.
        /// </summary>
        internal static string AddNewPictureLabel {
            get {
                return ResourceManager.GetString("AddNewPictureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Picture.
        /// </summary>
        internal static string AddPictureButton {
            get {
                return ResourceManager.GetString("AddPictureButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Picture.
        /// </summary>
        internal static string AddPicturePageTitle {
            get {
                return ResourceManager.GetString("AddPicturePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I see {0}.
        /// </summary>
        internal static string AddPictureResultDescription {
            get {
                return ResourceManager.GetString("AddPictureResultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And I think I recognize {0}.
        /// </summary>
        internal static string AddPictureResultLandmarkDescription {
            get {
                return ResourceManager.GetString("AddPictureResultLandmarkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong :( Here is a cat instead!.
        /// </summary>
        internal static string BingSearchServiceCatInsteadTitle {
            get {
                return ResourceManager.GetString("BingSearchServiceCatInsteadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseButtonText {
            get {
                return ResourceManager.GetString("CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nothing! No description found.
        /// </summary>
        internal static string ComputerVisionServiceNoDescription {
            get {
                return ResourceManager.GetString("ComputerVisionServiceNoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi there,.
        /// </summary>
        internal static string HiThereLabel {
            get {
                return ResourceManager.GetString("HiThereLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an image first.
        /// </summary>
        internal static string NoImageSelectedAlertContent {
            get {
                return ResourceManager.GetString("NoImageSelectedAlertContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image selected.
        /// </summary>
        internal static string NoImageSelectedAlertTitle {
            get {
                return ResourceManager.GetString("NoImageSelectedAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pictures yet, give me your best shots! 📸.
        /// </summary>
        internal static string NoPictureMessage {
            get {
                return ResourceManager.GetString("NoPictureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string NoTextEnteredAlertCancel {
            get {
                return ResourceManager.GetString("NoTextEnteredAlertCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t enter any text!.
        /// </summary>
        internal static string NoTextEnteredAlertContent {
            get {
                return ResourceManager.GetString("NoTextEnteredAlertContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No text entered.
        /// </summary>
        internal static string NoTextEnteredAlertTitle {
            get {
                return ResourceManager.GetString("NoTextEnteredAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string PictureFailedAlertCancel {
            get {
                return ResourceManager.GetString("PictureFailedAlertCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can you hand me my glasses? Something went wrong while analyzing this image.
        /// </summary>
        internal static string PictureFailedAlertContent {
            get {
                return ResourceManager.GetString("PictureFailedAlertContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uh-oh!.
        /// </summary>
        internal static string PictureFailedAlertTitle {
            get {
                return ResourceManager.GetString("PictureFailedAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendation.
        /// </summary>
        internal static string ReccomendationLabel {
            get {
                return ResourceManager.GetString("ReccomendationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string TakePhotoActionSheetCancel {
            get {
                return ResourceManager.GetString("TakePhotoActionSheetCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose photo.
        /// </summary>
        internal static string TakePhotoActionSheetChoose {
            get {
                return ResourceManager.GetString("TakePhotoActionSheetChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take photo.
        /// </summary>
        internal static string TakePhotoActionSheetTake {
            get {
                return ResourceManager.GetString("TakePhotoActionSheetTake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to do?.
        /// </summary>
        internal static string TakePhotoActionSheetTitle {
            get {
                return ResourceManager.GetString("TakePhotoActionSheetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to add picture.
        /// </summary>
        internal static string TapToAddPictureLabel {
            get {
                return ResourceManager.GetString("TapToAddPictureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to translate something?.
        /// </summary>
        internal static string TranslateTextEntryPlaceholder {
            get {
                return ResourceManager.GetString("TranslateTextEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string TranslationFailedAlertCancel {
            get {
                return ResourceManager.GetString("TranslationFailedAlertCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We lost our dictionary, something went wrong while translating.
        /// </summary>
        internal static string TranslationFailedAlertContent {
            get {
                return ResourceManager.GetString("TranslationFailedAlertContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whoops!.
        /// </summary>
        internal static string TranslationFailedAlertTitle {
            get {
                return ResourceManager.GetString("TranslationFailedAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text to translate.
        /// </summary>
        internal static string TranslationResultPageEntryPlaceholder {
            get {
                return ResourceManager.GetString("TranslationResultPageEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where do you want to go?.
        /// </summary>
        internal static string WhereDoYouWantLabel {
            get {
                return ResourceManager.GetString("WhereDoYouWantLabel", resourceCulture);
            }
        }
    }
}
